version: '3.8'

services:
  app:
    build: .
    ports:
      - "9091:9091"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres